# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'DiscoverPlaces' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!

  pod 'GooglePlaces', '3.7'
  pod 'SDWebImage', '5.5'
  pod 'Cosmos', '21.0'  

  target 'DiscoverPlacesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DiscoverPlacesUITests' do
    # Pods for testing
  end

end
